spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/whatsapp_db}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:@R1a2h3u4l5}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=HDvPk0MFXGBRM++orVbaP8IBMLnkmEOq0uyhNLGM6fc=
jwt.expiration=86400000
